### PR TITLE
Prevent console.error from going off because it causes some problems in test code

### PR DESCRIPTION
**Pull request by timotree3**
For example, [this CI run](https://github.com/holochain/elemental-chat-ui/runs/4025567093?check_suite_focus=true#step:5:63) fails to due to some `getFileName` error which I think is caused by the usage of `console.error`

### CODE REVIEW

**Comment by timotree3** [comment]
I may have merged #79 prematurely. When running tests on develop, I saw that 0 out of 0 tests passed, which counts as success :/ This PR now fixes that and additionally updates the lints to apply to the `tests/` folder

**Comment by timotree3** [comment]
I actually think jest is pointing us to a valid criticism of holochain-conductor-api. I don't think libraries should log things, and they should definitely not log errors under expected and normal circumstances. If we're looking for the proper solution here, I propose that we propagate this error properly. Perhaps a good solution would be to capture this error but not print it, and then edit the error path of `AppWebsocket.connect` to detect this error, and include it. e.g.

> Exception: Could not connect to holochain app websocket at localhost:xxxx
> Note: This may be because we are in a launcher environment and failed to detect that. Reason: ${launcherDetectionError}

**Comment by guillemcordoba** [comment]
So the problem is really that we can't hide the error in the browser, see https://stackoverflow.com/questions/12915582/eliminate-404-url-error-in-console and https://github.com/verlok/vanilla-lazyload/issues/460. When we do the `fetch` from a browser but not inside the launcher environment, we are going to get an error in the console, and we can't do anything for that. To avoid people being confused about that, I included the console.warn just after that to let the devs know that they don't have to worrry about that 404 error.

What we could do is do the fetch in the first `AppWebsocket.connect()`, and then it's not a side effect from importing the library... I like that more, but it still has the same problem with the 404 error, we can't really capture it.

Would you be okey if I did that change?

The thing you are running into is that Jest is not really a browser environment, so it shouldn't even do the fetch, but Jest tries to simulate a browser so we have thing like window set. Jest is weird...

**Comment by timotree3** [comment]
I could imagine wanting to test launcher autodetection using jest. maybe the best approach would be to revert to before this PR but just put the `console.warn` and `console.error` within an if that we are not inside jest?

**Comment by timotree3** [comment]
I will test out this version as requested.

**Review by guillemcordoba — APPROVED** [review]

**Pull request merged**
