### PR TITLE
Dump full state, importing lots of types from https://github.com/holochain-open-dev/core-types

### PR DESCRIPTION
**Pull request by guillemcordoba**
In the effort to make the Holochain Playground compatible with a real Holochain conductor, I've had to create all the types that the `dump_full_state` function is returning. I thought it would be useful to include them at the @holochain/conductor-api level, so that everyone gets them. Let me know if you'd prefer to keep them at https://github.com/holochain-open-dev/core-types.

### CODE REVIEW

**Comment by Connoropolous** [comment]
@guillemcordoba this still under consideration for review?

**Comment by guillemcordoba** [comment]
Yeap!

**Review by jost-s — APPROVED** [review]
This is brilliant, thanks so much @guillemcordoba !!!

I've included this work into the new repo of the JS client.

**Comment by jost-s** [comment]
I'm closing this PR regardless, because we're archiving the repo in favor of the new one.

**Comment by jost-s** [comment]
My mistake, we're not archiving this repo but only changing its name. Regardless, this branch's changes are included.

**Pull request closed without merging**
