### PR TITLE
Fix proxy this for emittery

### PR DESCRIPTION
**Pull request by ThetaSinner**
This addresses https://github.com/holochain/holochain-client-js/issues/195

### CODE REVIEW

**Comment by ThetaSinner** [comment]
I've struggled to reproduce this in Node tests. I can do it with JavaScript but whatever is happening there, TypeScript seems to fix. Without digging deeper into the Vue.js source I'm not sure what they are doing differently. Maybe somebody with better TypeScript knowledge can figure this one out.

I have installed this PR into my own project and it does fix the problem.

**Comment by ThetaSinner** [comment]
Not sure what's happening with the macos build, is this a new problem that's worth me digging into or something known that we can address?

**Comment by jost-s** [comment]
> Not sure what's happening with the macos build, is this a new problem that's worth me digging into or something known that we can address?

That's a problem with the nix install action. I upgraded it, that should fix it.

**Comment by ThetaSinner** [comment]
Awesome, thank you!

**Comment by jost-s** [comment]
@ThetaSinner Why do you want an AppAgentWs to be reactive? I see that @mattyg did that in mewsfeed, but I cannot see why that's necessary there, either. It seems like the AppAgentWs can just be a variable with `let` and doesn't need to be reactive.

**Comment by mattyg** [comment]
> @ThetaSinner Why do you want an AppAgentWs to be reactive? I see that @mattyg did that in mewsfeed, but I cannot see why that's necessary there, either. It seems like the AppAgentWs can just be a variable with `let` and doesn't need to be reactive.

It needs to be reactive so I can initialize it in the vue app's root component. Then I can display content while waiting for it to initialize, and when its ready, reactively make it available to sub-components via provide / inject. So it needs to reactively update the client variable from  `undefined` to the actual AppAgentWs. (also this is how the scaffolder implements it)

I just ran into this issue in another context where I am passing the AppAgentWebsocket into new class as a constructor param, and then trying to listen to signals within that class. Unfortunately this PR doesn't seem to resolve it in that case.

**Comment by ThetaSinner** [comment]
> @ThetaSinner Why do you want an AppAgentWs to be reactive? I see that @mattyg did that in mewsfeed, but I cannot see why that's necessary there, either. It seems like the AppAgentWs can just be a variable with let and doesn't need to be reactive.

@jost-s  Yes to what @mattyg said and I'm going to expand a little bit.
- I don't want the app to have to wait to render until the client is connected, all my structural components can render then I can render placeholders for anything that needs data until the client is connected.
- I don't want to have to reload the page if the connection to the back-end drops for any reason. I think it's simpler to reconnect a websocket and resume sending requests than it is to persist and recreate client state on reload.
- I don't want to pass the client through all my components in either React or Vue (I don't know anything about Svelte). In Vue provide/inject is the mechanism for deep passing, in React that would be a hook that provides the client. In either case the provide should be reactive so that the UI can proceed with rendering without waiting for a value.

I'm still experimenting but I've actually already taken this a [step further](https://github.com/ThetaSinner/h-drone-swarm/blob/main/ui/src/client/index.ts#L13) and wrapped the client. This lets me transparently reconnect the client which I can't do with this client because construction/connection is atomic. So I am injecting my client wrapper into the components that need it then they go ahead and render while creating a promise on `waitForConnected` that let's them fill or create in data once a client is available, regardless of which connection that is under the hood.

**Comment by ThetaSinner** [comment]
> I just ran into this issue in another context where I am passing the AppAgentWebsocket into new class as a constructor param, and then trying to listen to signals within that class. Unfortunately this PR doesn't seem to resolve it in that case.

@mattyg any chance you can point me at an example and I'll see if I can figure out why this isn't working everywhere?

**Comment by mattyg** [comment]
> > I just ran into this issue in another context where I am passing the AppAgentWebsocket into new class as a constructor param, and then trying to listen to signals within that class. Unfortunately this PR doesn't seem to resolve it in that case.
> 
> @mattyg any chance you can point me at an example and I'll see if I can figure out why this isn't working everywhere?

Well I tried to make an example, but it worked properly, and then I fixed it in my use case as well, so nevermind!

**Comment by ThetaSinner** [comment]
@mattyg Cool okay, if it pops up again feel free to send it my way :)

**Comment by jost-s** [comment]
@ThetaSinner With the wrapper, do you still need the Emittery workaround?

**Comment by jost-s** [comment]
@ThetaSinner I suppose so. I'll merge this, thanks you for the work!

**Review by jost-s — APPROVED** [review]

**Comment by ThetaSinner** [comment]
Sorry I hadn't got to this yet but yes, the Vue proxies are deep so even with a wrapper the `this` will move.

**Comment by jost-s** [comment]
> Sorry I hadn't got to this yet but yes, the Vue proxies are deep so even with a wrapper the `this` will move.

Right, okay. I have been unable to reproduce the problem too, even in a JS file using Vue's `ref` function.

**Comment by ThetaSinner** [comment]
The code I used to test the fix is

```js
import Emittery from 'emittery';

class T extends Emittery {
  constructor() {
    super();

    // // Ensure all super methods are bound to this instance because Emittery relies on `this` being the instance.
    // Object.getOwnPropertyNames(Emittery.prototype).forEach((name) => {
    //     if (typeof this[name] === 'function') {
    //         this[name] = this[name].bind(this);
    //     }
    // });
  }

  doOn(func) {
    console.log(this);
    this.on('hello', func);
  }
}

let t = new Proxy(new T(), {});
t.doOn(() => {
    console.log('got a hello');
});

t.emit('hello');
```

It can just be run with node and the fix can be commented in.

I get the same Emittery error I got from a Vue app

```
file:///home/thetasinner/source/holo/holochain-client-js/node_modules/emittery/index.js:27
        if (!events.has(eventName)) {
```

**Comment by jost-s** [comment]
Thanks for that. Do you have a clue why something like
```javascript
const appAgentWs = await AppAgentWs.connect(...);
const ws = ref(appAgentWs);
ws.value.client.on('signal', () => console.log('signalled'));
ws.value.client.emit('signal', ...);
```
works?

**Comment by ThetaSinner** [comment]
That does fail for me, if I do `npm i -D vue` and create a Javascript file called `test2.js` containing

```
import { AppAgentWebsocket } from './lib/index.js';
import { ref } from 'vue';

const appAgentWs = await AppAgentWebsocket.connect('ws://localhost:8080');
const ws = ref(appAgentWs);
ws.value.on('signal', (m) => console.log('signalled', m));
ws.value.emitter.emit('signal', {
    test: 'message'
});
```

I can then start a sandbox, run it with `hc sandbox run -p 8080` and run that script against it, I get an error

```
file:///home/thetasinner/source/holo/holochain-client-js/node_modules/emittery/index.js:27
        if (!events.has(eventName)) {
                    ^

TypeError: Cannot read properties of undefined (reading 'has')
    at getListeners (file:///home/thetasinner/source/holo/holochain-client-js/node_modules/emittery/index.js:27:14)
    at Proxy.on (file:///home/thetasinner/source/holo/holochain-client-js/node_modules/emittery/index.js:280:14)
    at Proxy.on (file:///home/thetasinner/source/holo/holochain-client-js/lib/api/app-agent/websocket.js:171:29)
    at file:///home/thetasinner/source/holo/holochain-client-js/test2.js:6:10
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

The test script runs fine if I comment my fix back in

**Pull request merged**
