### PR TITLE
Mistyped client call responses

### PR DESCRIPTION
**Pull request by mattyg**
Failing test demonstrating #265

### CODE REVIEW

**Comment by mattyg** [comment]
Heads up this is just a demonstration with one client call -- appInfo. The same issue needs to be resolved for all other client calls that take in hash types in their input type or have hash types in their responses.

For responses we have a simple solution: transform the response type and cast any Uint8Arrays representing hashes into a HoloHash instance.

For requests I don't know what the best solution is: do we want to require the input type to actually be HoloHash instances? Or do we want another set of types for when hashes are used in inputs, or type them all Uint8Array?

**Comment by mjbrisebois** [comment]
I think all inputs should accept `Uint8Array` and then it can be transformed to the expected hash type like the example in [utils/hash-parts.ts](https://github.com/holochain/holochain-client-js/blob/develop/src/utils/hash-parts.ts#L34-L35).

As for responses, I don't have a strong opinion.  However, I would lean towards the client not automatically transforming the payloads.

**Comment by jost-s** [comment]
I agree with both, inputs should accept `Uint8Array` and responses remain unaltered.
Perhaps inputs should actually accept both `Uint8Array` and `HoloHash` where applicable.

Would it be helpful to introduce another type which is `Uint8Array | HoloHash`? Actually I realize I need to discuss this in the office hours call next week. This change has wider implications than I saw.

**Comment by mattyg** [comment]
In that case why dont we just revert to using the original types? We can still use the @spartan-hc/holo-hash utility functiom implementations under-the-hood

**Comment by jost-s** [comment]
Reverted the spartan-hc changes.

**Pull request closed without merging**
